//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_MASTER
    {
        public int ACTIVITY_CODE { get; set; }
        public string ACTIVITY_NAME { get; set; }
        public string ACTIVITY_URL { get; set; }
        public int SERVICE_CODE { get; set; }
        public Nullable<bool> IS_MENU { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public long CREATEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<long> MODIFIEDBY { get; set; }
        public string IP { get; set; }
        public int DisplayOrder { get; set; }
        public string ACTIVITY_DISPLAY_NAME { get; set; }
        public bool IsMaster { get; set; }
        public bool ShowDependency { get; set; }
    }
}
