//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_ItemCategory_Master
    {
        public AM_ItemCategory_Master()
        {
            this.AM_Item_Master = new HashSet<AM_Item_Master>();
        }
    
        public int ItemCategory_Master_ID { get; set; }
        public string ItemCategory { get; set; }
        public int Asset_SubType_ID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long GoverningBodyID { get; set; }
        public Nullable<long> InstituteID { get; set; }
        public long CreatedByID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByIP { get; set; }
        public Nullable<long> ModifiedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedByIP { get; set; }
    
        public virtual ICollection<AM_Item_Master> AM_Item_Master { get; set; }
    }
}
